name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # Scan for common Rails security vulnerabilities using static analysis
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
  # Run RSpec tests
  test:
    runs-on: ubuntu-latest
    
    env:
      JWT_SEC: ""
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
      REDIS_URL: redis://localhost:6379/1
      GITHUB_CLIENT_ID: Ov23li7jAxwM2KO7uG0D
      GITHUB_CLIENT_SEC: ""
      DB_PRIMARY_HOST: ""
      DB_PRIMARY_PW: ""
      DB_PRIMARY_SSL_KEY: ""
      SECRET_KEY_BASE: 455784dfcdeaacb6e63af053e62dcd8481ba042c5fde14c2f825a032670007cda05331395113d5fd667f4ef05605247d93079d66053eb82cc906a70560723ee5
      SIDEKIQ_WEB_UI_PW: ""
      API_URL: http://localhost:3001
      FRONTEND_URL: http://localhost:3000

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Check database connection
        run: |
          echo "Testing PostgreSQL connection..."
          PGPASSWORD=postgres psql -h localhost -U postgres -c "SELECT 1"

      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec spec